#!/bin/sh

PKGNAME="$1"

# check param (node module name)
if [[ "x${PKGNAME}" == "x" || \
        "x${PKGNAME}" == "x--help" || \
        "x${PKGNAME}" == "x-h" ]]; then
    echo "Usage: $(basename "$0") module_name"
    exit 0
fi

# check npm command
if ! which npm 1>/dev/null 2>&1; then
    echo "npm: command not found."
    echo "You need to install package \"nodejs\" from SBo repository."
    exit 1
fi

BUILD=""
TAG="myreq"
PKGTYPE="txz"
OUTPUT="/root/src"
TMP="/tmp/${PKGNAME}-build/"

rm -rf "${TMP}"
mkdir -p "${TMP}"
cd "${TMP}" || exit 1

DESTDIR=./ npm install -g "${PKGNAME}" || exit 1

ARCH=""
[ "$(uname -m)" == "x86_64" ] && ARCH="64"

if [ -n "${ARCH}" ]; then
    mv usr/lib usr/lib64
    (
        cd usr/bin || exit 1
        FILES=$(ls)
        for FILE in ${FILES}; do
            if [ -L "${FILE}" ]; then
                TARGET=$(readlink "${FILE}")
                rm "${FILE}"
                ln -s "$(echo "${TARGET}" | sed -e 's/\/lib\//\/lib64\//g')" \
                    "${FILE}"
            fi
        done
    )
fi

# remove empty /usr/etc directory
[ -d usr/etc ] && \
    [[ "x$(find usr/etc -type f -o -type l  | wc -l)" == "x0" ]] && \
    rm -rf usr/etc

JSON="usr/lib${ARCH}/node_modules/${PKGNAME}/package.json"
VERSION=$(grep -i "\"version\":" "${JSON}" | cut -d \" -f 4 | tr - .)
DESCRIPTION=$(grep -i "\"description\":" "${JSON}" | cut -d \" -f 4)
HOMEPAGE=$(grep -i "\"homepage\":" "${JSON}" | cut -d \" -f 4)

mkdir install
cat << EOF > install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.
       |-----handy-ruler-------------------------------------------------------|
${PKGNAME}: (${PKGNAME})
${PKGNAME}:
${PKGNAME}:
${PKGNAME}: ${DESCRIPTION}
${PKGNAME}:
${PKGNAME}:
${PKGNAME}:
${PKGNAME}:
${PKGNAME}:
${PKGNAME}: Homepage: ${HOMEPAGE}
${PKGNAME}:
EOF

mkdir -p "${OUTPUT}"
PACKAGE="${OUTPUT}/${PKGNAME}_npm-${VERSION}-noarch-${BUILD}${TAG}.${PKGTYPE}"
rm -f "${PACKAGE}"
makepkg -l y -c n "${PACKAGE}"
